#!/bin/bash

# If any step of the installation fails, we should exit with a failure
set -e

# Be extra verbose
set -x

cd `mktemp -d /tmp/nr-brewery-XX`
curl -fsSL https://github.com/newrelic/brewery/tarball/master | tar xz -m --strip 1

./setup/xcode-cli
./setup/brew
./setup/git

./setup/ruby
./setup/data-stores
./setup/docker

./setup/java
./setup/javascript
