
install memcached
install mysql55
install elasticsearch
install redis
install postgresql

services start memcached
services start mysql55
services start elasticsearch
services start redis
services start postgresql
