doctor
update

tap homebrew/versions
# https://github.com/Homebrew/homebrew-versions

install caskroom/cask/brew-cask
# https://github.com/caskroom/homebrew-cask/

install git
install rbenv
install ruby-build

# Apps
cask install hipchat
cask install sequel-pro
cask install google-chrome
cask install iterm2

# handy stuff
cask install qlstephen quicklook-json quicklook-csv qlmarkdown
