#!/bin/bash

ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"

brew doctor
brew update

brew tap homebrew/versions
# https://github.com/Homebrew/homebrew-versions

brew install caskroom/cask/brew-cask
# https://github.com/caskroom/homebrew-cask/
