#!/bin/bash

# Be extra verbose
set -x

# Install the various data-stores
mkdir -p ~/Library/LaunchAgents
brew tap homebrew/versions
for DATASTORE in memcached redis postgresql mysql56; do
  # Install the service, iff needed
  if [ $(($(brew list --versions $DATASTORE) + 0)) -eq 0 ]; then
    brew install $DATASTORE
  fi

  # Set service up to run automatically
  if [ $(($(brew list --versions $DATASTORE) + 0)) -eq 1 ]; then
    ln -sfv /usr/local/opt/$DATASTORE/*.plist ~/Library/LaunchAgents
  else
    echo "WARNING: Couldn't set $DATASTORE to auto-start because multiple versions are installed."
  fi
done

launchctl load ~/Library/LaunchAgents/homebrew*.plist
sleep 5

# Ensure postgres db exists, ignoring any messages about it already existing in the event this
# script needs to be re-run
createdb $USER |
  grep -v "database \"$USER\" already exists" 1>&2
