#!/bin/bash

# Install the various data-stores
brew install memcached
brew install mysql55
brew install elasticsearch
brew install redis
brew install postgresql

# Set them up to run automatically
mkdir -p ~/Library/LaunchAgents
brew services start memcached
brew services start mysql55
brew services start elasticsearch
brew services start redis
brew services start postgresql

# Setup postgres db
createdb $USER
