#!/bin/bash

brew install rbenv
brew install rbenv-gemset
brew install ruby-build

echo 'eval "$(rbenv init -)"' >> ~/.bash_profile
source ~/.bash_profile

# Install the current and next ruby version used by RPM
rbenv install 2.1.3
rbenv install 2.2.1

rbenv shell 2.1.3
gem install bundler

rbenv shell 2.2.1
gem install bundler
