#!/bin/bash

# TODO: Is Dogestry only relevant to Tools / Site-Engineering?
for TOOL in dogestry; do
  brew cask list $TOOL > /dev/null 2>&1
  if [ $? -ne 0 ]; then
    brew cask install $TOOL
  fi
done
