#!/bin/bash

xcode-select --install

# GUI interaction needed
sleep 1
osascript -e 'tell application "System Events" to keystroke return'

sleep 1
osascript -e 'tell application "System Events" to click button "Agree" of window "License Agreement" of process "Install Command Line Developer Tools"'
